/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author samanthadennison <your.name your.org>
 */
public class ManagerInterface extends javax.swing.JFrame {

    /**
     * Creates new form ManagerInterface
     */
    public ManagerInterface() {
        initComponents();
        updateAll();
        updateTenantStatusLabel.setVisible(false);
        deleteTenantStatusLabel.setVisible(false);
        apartmentStatusLabel.setVisible(false);
        deleteTeamMemberStatusLabel.setVisible(false);
        newTenantLabel.setVisible(false);
        newTeamMemberLabel.setVisible(false);
        
    }
    
    public void updateAll(){
        // Fills combo boxes with all tenants
        ArrayList<TenantAccount> tenantList = Tenant.allTenants();
        ArrayList<String> tenantIDList = new ArrayList<String>();
        tenantIDList.add("- Select One -");
        for (TenantAccount ten: tenantList){
            String id = ten.getId();
            tenantIDList.add(id);
        }
        updateTenantIDComboBox.setModel(new javax.swing.DefaultComboBoxModel(tenantIDList.toArray()));
        deleteTenantIDComboBox.setModel(new javax.swing.DefaultComboBoxModel(tenantIDList.toArray()));
        
        if (tenantList.size() >= 1){
            String tenantId = tenantList.get(tenantList.size()-1).getId();
            String tenantNum = tenantId.substring(1);
            int tenNum =  Integer.valueOf(tenantNum);
            String newTenantId = "T"+Integer.toString(tenNum+1);
            tenantIDTextField.setText(newTenantId);
            
            String tenantPassword = tenantList.get(tenantList.size()-1).getPassword();
            String tenantPasswordNum = tenantPassword.substring(1);
            int tenNumPassword = Integer.valueOf(tenantPasswordNum);
            String newTenantPassword = "T" + Integer.toString(tenNumPassword+1);
            passwordTextField.setText(newTenantPassword);
        }
        else{
            tenantIDTextField.setText("T1");
            passwordTextField.setText("T11111111");
        }
        
        // Fills combo boxes will all team members
        ArrayList<TeamMemberAccount> teamList = TeamMember.allTeamMembers();
        ArrayList<String> teamIDList = new ArrayList<String>();
        teamIDList.add("- Select One -");
        for (TeamMemberAccount mtm: teamList){
            String idMtm = mtm.getId();
            teamIDList.add(idMtm);
        }
        deleteTeamMemberComboBox.setModel(new javax.swing.DefaultComboBoxModel(teamIDList.toArray()));
        
        if (teamList.size() >= 1){
            String teamId = teamList.get(teamList.size()-1).getId();
            String teamNum = teamId.substring(1);
            int tNum =  Integer.valueOf(teamNum);
            String newTeamId = "M"+Integer.toString(tNum+1);
            teamMemberIDTextField.setText(newTeamId);
            
            String teamPassword = teamList.get(teamList.size()-1).getPassword();
            String teamPasswordNum = teamPassword.substring(1);
            int teamNumPassword =  Integer.valueOf(teamPasswordNum);
            String newTeamPassword = "M" + Integer.toString(teamNumPassword+1);
            teamPasswordTextField.setText(newTeamPassword);
        }
        else{
            teamMemberIDTextField.setText("M1");
            teamPasswordTextField.setText("M11111111");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tenantIDTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tenantNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        apartmentNumberTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailAddressTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        checkInTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checkOutTextField = new javax.swing.JTextField();
        addNewTenantButton = new javax.swing.JButton();
        newTenantLabel = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        deleteTenantIDComboBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        deleteTenantStatusLabel = new javax.swing.JLabel();
        deleteAccountButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        newApNumTextField = new javax.swing.JTextField();
        updateTenantStatusLabel = new javax.swing.JLabel();
        updateAccountButton = new javax.swing.JButton();
        apartmentStatusLabel = new javax.swing.JLabel();
        updateTenantIDComboBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        teamMemberIDTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        teamMemberNameTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        phoneMTMTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        emailMTMTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        newTeamMemberLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        teamPasswordTextField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        deleteTeamMemberComboBox = new javax.swing.JComboBox<>();
        deleteTeamMemberButton = new javax.swing.JButton();
        deleteTeamMemberStatusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        jPanel1.setBackground(new java.awt.Color(213, 232, 212));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 400));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Apartment Maintenance");

        jTabbedPane1.setBackground(new java.awt.Color(109, 135, 100));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTabbedPane2.setBackground(new java.awt.Color(109, 135, 100));
        jTabbedPane2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(213, 232, 212));
        jPanel4.setPreferredSize(new java.awt.Dimension(700, 400));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Add New Tenant Account");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Tenant ID:");

        tenantIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantIDTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("Tenant Name:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Apartment Number:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setText("Phone Number:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setText("Email Address:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setText("Date of Check-In:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setText("Date of Check-Out:");

        addNewTenantButton.setBackground(new java.awt.Color(109, 135, 100));
        addNewTenantButton.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        addNewTenantButton.setText("Add New Tenant");
        addNewTenantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewTenantButtonActionPerformed(evt);
            }
        });

        newTenantLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        newTenantLabel.setText("New Tenant");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel22.setText("New Password:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(apartmentNumberTextField))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tenantIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emailAddressTextField))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkOutTextField))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tenantNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(passwordTextField))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(addNewTenantButton))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(checkInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(newTenantLabel)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tenantIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(apartmentNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tenantNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(emailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(checkInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(checkOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(newTenantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewTenantButton)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add", jPanel4);

        jPanel6.setBackground(new java.awt.Color(213, 232, 212));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 0));
        jLabel13.setText("Delete Tenant Account");

        deleteTenantIDComboBox.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        deleteTenantIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        deleteTenantIDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTenantIDComboBoxActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel15.setText("Tenant ID:");

        deleteTenantStatusLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deleteTenantStatusLabel.setText("Tenant ID:");

        deleteAccountButton.setBackground(new java.awt.Color(109, 135, 100));
        deleteAccountButton.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        deleteAccountButton.setText("Delete Account");
        deleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteTenantStatusLabel)
                            .addComponent(jLabel15))
                        .addGap(40, 40, 40)
                        .addComponent(deleteTenantIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGap(246, 246, 246))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(deleteAccountButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTenantIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(deleteTenantStatusLabel)
                .addGap(38, 38, 38)
                .addComponent(deleteAccountButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Delete", jPanel6);

        jPanel5.setBackground(new java.awt.Color(213, 232, 212));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 0));
        jLabel10.setText("Update Tenant Account");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel11.setText("Tenant ID:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel12.setText("New Apartment Number:");

        newApNumTextField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        updateTenantStatusLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateTenantStatusLabel.setText("Tenant ID:");

        updateAccountButton.setBackground(new java.awt.Color(109, 135, 100));
        updateAccountButton.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        updateAccountButton.setText("Update Account");
        updateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAccountButtonActionPerformed(evt);
            }
        });

        apartmentStatusLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        apartmentStatusLabel.setText("Apartment filled");

        updateTenantIDComboBox.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        updateTenantIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        updateTenantIDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTenantIDComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(246, 246, 246))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(updateAccountButton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(updateTenantIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(updateTenantStatusLabel))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newApNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(apartmentStatusLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(newApNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateTenantIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateTenantStatusLabel)
                    .addComponent(apartmentStatusLabel))
                .addGap(63, 63, 63)
                .addComponent(updateAccountButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Update", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tenant Account", jPanel2);

        jPanel3.setBackground(new java.awt.Color(109, 135, 100));

        jTabbedPane3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jPanel7.setBackground(new java.awt.Color(109, 135, 100));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(213, 232, 212));
        jLabel14.setText("Add Maintenance Team Member Account");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Team Member ID:");

        teamMemberIDTextField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        teamMemberIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamMemberIDTextFieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Team Member Name:");

        teamMemberNameTextField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Phone Number:");

        phoneMTMTextField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Email Address:");

        emailMTMTextField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        addButton.setBackground(new java.awt.Color(159, 179, 152));
        addButton.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        addButton.setText("Add Account");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        newTeamMemberLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        newTeamMemberLabel.setForeground(new java.awt.Color(255, 255, 255));
        newTeamMemberLabel.setText("New Team Member");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Password:");

        teamPasswordTextField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(newTeamMemberLabel))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(addButton))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(teamPasswordTextField))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(teamMemberIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(26, 26, 26)
                                .addComponent(phoneMTMTextField)))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(teamMemberNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(emailMTMTextField)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(teamMemberIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(teamMemberNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(phoneMTMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(emailMTMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(teamPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newTeamMemberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Add", jPanel7);

        jPanel8.setBackground(new java.awt.Color(109, 135, 100));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(213, 232, 212));
        jLabel20.setText("Delete Maintenance Team Member Account");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Team Member ID:");

        deleteTeamMemberComboBox.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        deleteTeamMemberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        deleteTeamMemberComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTeamMemberComboBoxActionPerformed(evt);
            }
        });

        deleteTeamMemberButton.setBackground(new java.awt.Color(159, 179, 152));
        deleteTeamMemberButton.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        deleteTeamMemberButton.setText("Delete Account");
        deleteTeamMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTeamMemberButtonActionPerformed(evt);
            }
        });

        deleteTeamMemberStatusLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deleteTeamMemberStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        deleteTeamMemberStatusLabel.setText("Team Member ID:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(168, 168, 168))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(deleteTeamMemberStatusLabel))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(deleteTeamMemberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(deleteTeamMemberButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(deleteTeamMemberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(deleteTeamMemberStatusLabel)
                .addGap(26, 26, 26)
                .addComponent(deleteTeamMemberButton)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Delete", jPanel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Maintenance Team Member Account", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewTenantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewTenantButtonActionPerformed
        // TODO add your handling code here:
        boolean valid = true;
        String id = tenantIDTextField.getText();
        String name = tenantNameTextField.getText();
        String apNum = apartmentNumberTextField.getText();
        String phone = phoneNumberTextField.getText();
        String email = emailAddressTextField.getText();
        String checkIn = checkInTextField.getText();
        String checkOut = checkOutTextField.getText();
        String password = passwordTextField.getText();
        if (name.equals("") || apNum.equals("") || phone.equals("") || email.equals("") || 
                checkIn.equals("") || checkOut.equals("")){
            valid = false;
            
        }
        if (valid == true){
            TenantAccount Ten = new TenantAccount(id, name, apNum, phone, email, checkIn, checkOut, password);
            Tenant.addTenant(Ten);
            updateAll();
            tenantNameTextField.setText("");
            apartmentNumberTextField.setText("");
            phoneNumberTextField.setText("");
            emailAddressTextField.setText("");
            checkInTextField.setText("");
            checkOutTextField.setText("");
            newTenantLabel.setText(name + " has been added as a new tenant");
            newTenantLabel.setVisible(true);
        }
        else{
            newTenantLabel.setText("All fields must be completed");
            newTenantLabel.setVisible(true);
        }
        
        
    }//GEN-LAST:event_addNewTenantButtonActionPerformed

    private void updateTenantIDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTenantIDComboBoxActionPerformed
        // TODO add your handling code here:
        String id = String.valueOf(updateTenantIDComboBox.getSelectedItem());
        ArrayList<TenantAccount> tenantList = Tenant.allTenants();
        String tenantName = " ";
        for (TenantAccount ten: tenantList){
            String tenID = ten.getId();          
            if (tenID.equals(id)){
                tenantName = ten.getName();
            }
        }
        updateTenantStatusLabel.setText("Tenant Name: " + tenantName);
        updateTenantStatusLabel.setVisible(true);
        
    }//GEN-LAST:event_updateTenantIDComboBoxActionPerformed

    private void updateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAccountButtonActionPerformed
        // TODO add your handling code here:
        String newApNum = newApNumTextField.getText();
        String id = String.valueOf(updateTenantIDComboBox.getSelectedItem());
        boolean apEmpty = true;
        ArrayList<TenantAccount> tenantList = Tenant.allTenants();
        TenantAccount accountToUpdate = tenantList.get(0);
        for (TenantAccount ten: tenantList){
            String apNum = ten.getApNum();
            if (apNum.equals(newApNum)){
                apEmpty = false;
            }
            if(id.equals(ten.getId())){
                accountToUpdate = ten;
            }
        }
        if (apEmpty == true){
            String originalApNum = accountToUpdate.getApNum();
            Tenant.updateTenant(accountToUpdate, newApNum);
            apartmentStatusLabel.setText("Apartment number changed from " + originalApNum + " to " + newApNum + ".");
            apartmentStatusLabel.setVisible(true);
        }
        else{
            apartmentStatusLabel.setText("This apartment is not empty.");
            apartmentStatusLabel.setVisible(true);
        }
        newApNumTextField.setText("");
        
    }//GEN-LAST:event_updateAccountButtonActionPerformed

    private void deleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountButtonActionPerformed
        // TODO add your handling code here:
        String id = String.valueOf(deleteTenantIDComboBox.getSelectedItem());
        ArrayList<TenantAccount> tenantList = Tenant.allTenants();
        TenantAccount accountToUpdate = tenantList.get(0);
        String name = tenantList.get(0).getName();
        for (TenantAccount ten: tenantList){
            if(id.equals(ten.getId())){
                name = ten.getName();
                accountToUpdate = ten;
            }
        }
        Tenant.deleteTenant(accountToUpdate);
        updateAll();
        deleteTenantStatusLabel.setText("Tenant " + name + "'s account has been deleted");
        deleteTenantStatusLabel.setVisible(true);
    }//GEN-LAST:event_deleteAccountButtonActionPerformed

    private void deleteTenantIDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTenantIDComboBoxActionPerformed
        // TODO add your handling code here:
        String id = String.valueOf(deleteTenantIDComboBox.getSelectedItem());
        ArrayList<TenantAccount> tenantList = Tenant.allTenants();
        String name = tenantList.get(0).getName();
        for (TenantAccount ten: tenantList){
            if(id.equals(ten.getId())){
                name = ten.getName();
            }
        }
        deleteTenantStatusLabel.setText("Tenant Name: " + name);
        deleteTenantStatusLabel.setVisible(true);
        
    }//GEN-LAST:event_deleteTenantIDComboBoxActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        boolean valid = true;
        String id = teamMemberIDTextField.getText();
        String name = teamMemberNameTextField.getText();
        String phone = phoneMTMTextField.getText();
        String email = emailMTMTextField.getText();
        String password = teamPasswordTextField.getText();
        if (name.equals("") || phone.equals("") || email.equals("")){
            valid = false;
            
        }
        if (valid == true){
            TeamMemberAccount team = new TeamMemberAccount(id, name, phone, email, password);
            TeamMember.addTeamMember(team);
            updateAll();
            teamMemberNameTextField.setText("");
            phoneMTMTextField.setText("");
            emailMTMTextField.setText("");
            newTeamMemberLabel.setText(name + " has been added as a new team member");
            newTeamMemberLabel.setVisible(true);
        }
        else{
            newTeamMemberLabel.setText("All fields must be completed");
            newTeamMemberLabel.setVisible(true);
        }
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteTeamMemberComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTeamMemberComboBoxActionPerformed
        // TODO add your handling code here:
        String id = String.valueOf(deleteTeamMemberComboBox.getSelectedItem());
        ArrayList<TeamMemberAccount> teamList = TeamMember.allTeamMembers();
        String name = teamList.get(0).getName();
        for (TeamMemberAccount mtm: teamList){
            if(id.equals(mtm.getId())){
                name = mtm.getName();
            }
        }
        deleteTeamMemberStatusLabel.setText("Team Member Name: " + name);
        deleteTeamMemberStatusLabel.setVisible(true);
    }//GEN-LAST:event_deleteTeamMemberComboBoxActionPerformed

    private void deleteTeamMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTeamMemberButtonActionPerformed
        // TODO add your handling code here:
        String id = String.valueOf(deleteTeamMemberComboBox.getSelectedItem());
        ArrayList<TeamMemberAccount> teamList = TeamMember.allTeamMembers();
        TeamMemberAccount accountToUpdate = teamList.get(0);
        String name = teamList.get(0).getName();
        for (TeamMemberAccount mtm: teamList){
            if(id.equals(mtm.getId())){
                name = mtm.getName();
                accountToUpdate = mtm;
            }
        }
        TeamMember.deleteTeamMember(accountToUpdate);
        updateAll();
        deleteTeamMemberStatusLabel.setText("Team Member " + name + "'s account has been deleted");
        deleteTeamMemberStatusLabel.setVisible(true);
    }//GEN-LAST:event_deleteTeamMemberButtonActionPerformed

    private void tenantIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenantIDTextFieldActionPerformed

    private void teamMemberIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamMemberIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamMemberIDTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addNewTenantButton;
    private javax.swing.JTextField apartmentNumberTextField;
    private javax.swing.JLabel apartmentStatusLabel;
    private javax.swing.JTextField checkInTextField;
    private javax.swing.JTextField checkOutTextField;
    private javax.swing.JButton deleteAccountButton;
    private javax.swing.JButton deleteTeamMemberButton;
    private javax.swing.JComboBox<String> deleteTeamMemberComboBox;
    private javax.swing.JLabel deleteTeamMemberStatusLabel;
    private javax.swing.JComboBox<String> deleteTenantIDComboBox;
    private javax.swing.JLabel deleteTenantStatusLabel;
    private javax.swing.JTextField emailAddressTextField;
    private javax.swing.JTextField emailMTMTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField newApNumTextField;
    private javax.swing.JLabel newTeamMemberLabel;
    private javax.swing.JLabel newTenantLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField phoneMTMTextField;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JTextField teamMemberIDTextField;
    private javax.swing.JTextField teamMemberNameTextField;
    private javax.swing.JTextField teamPasswordTextField;
    private javax.swing.JTextField tenantIDTextField;
    private javax.swing.JTextField tenantNameTextField;
    private javax.swing.JButton updateAccountButton;
    private javax.swing.JComboBox<String> updateTenantIDComboBox;
    private javax.swing.JLabel updateTenantStatusLabel;
    // End of variables declaration//GEN-END:variables
}
